### ISSUE TITLE
Not an issue but a proposal

### ISSUE THREAD

**Issue by DenB10** [itagagaki/DeepL-Selected-Text#1]
A few days ago, I wrote on ATN a review for your add-on to say how good I thought it was and to give you some suggestions for improvement.
You have since made some of these improvements and I am grateful for that. Also, I offer you my contribution with its translation in French that you can integrate if you are interested of course. You can find it here: https://we.tl/t-NiHBsrNovi
Greetings from France,
DenBar

**Comment by itagagaki** [comment]
Hi DenBar,

I'm late in seeing this, so the contribution you would have sent me had already been expired.
I'm sorry, but can you send it again? Of course your contribution is welcome!

**Comment by DenB10** [comment]
Hi itagagaki,

No problem, new WeTransfer download link: https://we.tl/t-mofcBU1MBq

If you want to add the translation of the extension shortcut description (manifest.json file), here it is :
"Translate selected text with DeepL" -> "Traduire le texte sélectionné avec DeepL"

Best regards,

DenBar

**Comment by itagagaki** [comment]
I added the French locale that DenBar contributed to me to the add-on. And the new version 1.2.1 is now available on ATN.
https://addons.thunderbird.net/addon/deepl-selected-text/

Thanks to DenBar for this.
Profitez-en !
Et s'il vous plaît, continuez à les faire venir !

**Comment by DenB10** [comment]
どういたしまして
それは私にとっても嬉しいことです!
