### ISSUE TITLE
Unable to close the Deepl window using keyboard shortcut

### ISSUE THREAD

**Issue by HugoGresse** [itagagaki/DeepL-Selected-Text#5]
When opening the Deepl in a new window (not tab), the CTRL + W (or CMD + W) does not close it.

**Comment by itagagaki** [comment]
Thanks for the report. Investigating how to resolve this issue.

**Comment by itagagaki** [comment]
I reported this issue to the Thunderbird developers and they have started working on improvements.
Let's wait for the good news.
https://bugzilla.mozilla.org/show_bug.cgi?id=1796973
https://phabricator.services.mozilla.com/D160071

**Comment by HugoGresse** [comment]
Woaw, did not thought it will be to the Thunberbird bugzilla. Thanks for digging into it.

**Comment by itagagaki** [comment]
This seems to have improved with the Thunderbird 115.
