### ISSUE TITLE
does not work in Thunderbird 102.13.* anymore

### ISSUE THREAD

**Issue by MarkyMarkDE** [itagagaki/DeepL-Selected-Text#7]
unfortunately the addon no longer works in thunderbird 102.13.*.
Numerous error messages appear in the error console. It would be nice to fix the addon again.

These are the errors:

19:41:17.801 TypeError: PrecompiledScript.executeInGlobal: Argument 1 is not an object. ExtensionContent.jsm:574:25
19:41:19.353 TypeError: r is null translator_late.min.$4e2dab.js:44:688844
19:41:22.730 sendRemoveListener on closed conduit languagetool-mailextension@languagetool.org.1649267441664 2 ConduitsChild.jsm:112

**Comment by itagagaki** [comment]
Perhaps the version of Thunderbird seems irrelevant.
Could you try this measure? --> #6

**Comment by itagagaki** [comment]
It is working on 102.13.0 at my end.
First, could you try disabling other add-ons, if any?

**Comment by MarkyMarkDE** [comment]
i have had disabled all other addons and nothing worked, maybe it's an OS specific bug?
Im on Ubuntu 22.04.2 (Wayland)

07:42:51.743 Das Cookie "rgReload" wurde abgelehnt, da es bereits abgelaufen ist. translator
07:42:51.743 Das Cookie "dapUid" wurde abgelehnt, da es bereits abgelaufen ist. translator
07:42:52.624 TypeError: r is null translator_late.min.$4e2dab.js:44:688844

**Comment by itagagaki** [comment]
Now then, please try the solutions described in #6

**Comment by itagagaki** [comment]
Duplicate #6
